---
title: "readme"
#author: "Paul Q. Sims"
#date: "7/13/2020"
output: github_document
---

## Description

Data and code associated with the study “An investigation of population variation in maze exploration and its predictors in wild Trinidadian guppies (*Poecilia reticulata*)”. *In prep*. This repository will be permanently archived at Zenodo. 

A report summary containing all the R script output can be found at [reports/analysis-summary.md](https://github.com/paulqsims/inno_pop/blob/master/reports/analysis-summary.md)

R Markdown files can be rendered by sourcing [R/render-Rmd.R](https://github.com/paulqsims/inno_pop/blob/master/R/render-Rmd.R)

## Authors

Paul Q. Sims (<paul.q.sims@gmail.com>)

Simon M. Reader (<simon.reader@mcgill.ca>)

## Directory structure

* `data/` Data used in analyses
* `R/` Self-contained R markdown (*.Rmd) scripts (can be run on their own) and functions used for the analyses and in generating plots
* `figs/` High quality figures generated for publication
* `reports/` Markdown and html summaries of code output

## Prerequisites: R packages

Data clean up

* `tidyverse`
* `broom`, `broom.mixed`

Analyses

* `nlme`
* `MuMIn`

Plots

* `ggplot2`
* `ggsignif`
* `scales`
* `effects`

Misc

* `rprojroot`, `here`
* `rmarkdown`, `knitr`

## Metadata

Reference file: [data_Sims-Reader_2020.csv](https://github.com/paulqsims/inno_pop/blob/master/data/data_Sims-Reader_2020.csv)

```{r, echo = FALSE, results = TRUE, message = FALSE}

library(tidyverse)

data_analysis <- 
  read_csv("data/data_Sims-Reader_2020.csv")

# Write out descriptions associated with each column header
var_names <- names(data_analysis) %>%
  append(., c("LN suffix", "sc suffix"))
var_descrip <- c(
  "Population: Lower or upper Aripo",
  "Site sampled",
  "Unique site identifier",
  "Trial: 1 or 2",
  "Group id",
  "Latency to reach the goal zone, zone 11, (sec)",
  "Total zones entered",
  "Body length (mm)",
  "Improvement ratio learning measure = goal zone latency on trial 2/goal zone latency on trial 1",
  "Natural log transformation",
  "Mean centered and standardized by 1 standard deviation")

var_metadata <- tibble(var_names,var_descrip) %>%
                  rename(Column = "var_names", Description = "var_descrip")

knitr::kable(var_metadata)
```

## License

This software is licensed under the MIT License and the data is licensed under CC0 - see the [LICENSE.md](https://github.com/paulqsims/inno_pop/blob/master/license.md) file for details.

## Funding information

This work was supported by the Natural Sciences and Engineering Research Council of Canada (NSERC; Discovery grants #418342-2012 and 429385-2012) and the Canada Foundation for Innovation (grant #29433).

